// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {localfs} from '../models';
import {core} from '../models';
import {queue} from '../models';

export function ConnectSite(arg1:number):Promise<void>;

export function DeleteSite(arg1:number):Promise<void>;

export function DisconnectSite(arg1:number):Promise<void>;

export function ListLocal(arg1:string):Promise<localfs.Listing>;

export function ListRemote(arg1:number,arg2:string):Promise<core.Listing>;

export function LocalHome():Promise<string>;

export function LocalRoots():Promise<Array<localfs.Root>>;

export function ResolvePrompt(arg1:string,arg2:boolean):Promise<void>;

export function SaveSite(arg1:queue.Site,arg2:string):Promise<queue.Site>;

export function SchemaVersion():Promise<number>;

export function Sites():Promise<Array<queue.Site>>;
