// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {localfs} from '../models';

export function ListLocal(arg1:string):Promise<localfs.Listing>;

export function LocalHome():Promise<string>;

export function LocalRoots():Promise<Array<localfs.Root>>;

export function SchemaVersion():Promise<number>;
