// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelTransfer(arg1) {
  return window['go']['main']['App']['CancelTransfer'](arg1);
}

export function ClearDoneTransfers() {
  return window['go']['main']['App']['ClearDoneTransfers']();
}

export function ConnectSite(arg1) {
  return window['go']['main']['App']['ConnectSite'](arg1);
}

export function DeleteSite(arg1) {
  return window['go']['main']['App']['DeleteSite'](arg1);
}

export function DisconnectSite(arg1) {
  return window['go']['main']['App']['DisconnectSite'](arg1);
}

export function EnqueueDownloads(arg1, arg2, arg3) {
  return window['go']['main']['App']['EnqueueDownloads'](arg1, arg2, arg3);
}

export function ListLocal(arg1) {
  return window['go']['main']['App']['ListLocal'](arg1);
}

export function ListRemote(arg1, arg2) {
  return window['go']['main']['App']['ListRemote'](arg1, arg2);
}

export function LocalHome() {
  return window['go']['main']['App']['LocalHome']();
}

export function LocalRoots() {
  return window['go']['main']['App']['LocalRoots']();
}

export function PauseTransfer(arg1) {
  return window['go']['main']['App']['PauseTransfer'](arg1);
}

export function RemoteHome(arg1) {
  return window['go']['main']['App']['RemoteHome'](arg1);
}

export function ResolvePrompt(arg1, arg2) {
  return window['go']['main']['App']['ResolvePrompt'](arg1, arg2);
}

export function ResumeTransfer(arg1) {
  return window['go']['main']['App']['ResumeTransfer'](arg1);
}

export function SaveSite(arg1, arg2) {
  return window['go']['main']['App']['SaveSite'](arg1, arg2);
}

export function SchemaVersion() {
  return window['go']['main']['App']['SchemaVersion']();
}

export function Sites() {
  return window['go']['main']['App']['Sites']();
}

export function TransfersList() {
  return window['go']['main']['App']['TransfersList']();
}
